[workspace]
members = ["packages/vibe-core", "apps/native/src-tauri"]
resolver = "2"

[workspace.dependencies]
eyre = { version = "0.6", features = ["auto-install"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = ["macros", "rt", "rt-multi-thread"] }

# Optimize for release builds
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
