/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScreenSource {
  id: string
  name: string
  width: number
  height: number
  isDisplay: boolean
}
export interface AudioDevice {
  id: string
  name: string
  deviceType: string
}
export interface RecordingConfiguration {
  width?: number
  height?: number
  fps?: number
  showCursor?: boolean
  captureAudio?: boolean
  audioDeviceId?: string
  outputPath: string
  pixelFormat?: string
  colorSpace?: string
}
export declare function initScreencapturekit(): void
export declare function getVersion(): string
export declare function checkMacosVersion(): string
export declare class ScreenCaptureKitRecorder {
  constructor()
  /** Get available screen sources (displays and windows) */
  getAvailableScreens(): Array<ScreenSource>
  /** Get available audio devices */
  getAvailableAudioDevices(): Array<AudioDevice>
  /** Start recording with the given configuration */
  startRecording(screenId: string, config: RecordingConfiguration): void
  /** Stop the current recording */
  stopRecording(): string
  /** Check if currently recording */
  isRecording(): boolean
  /** Get recording status */
  getStatus(): string
}
