/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScreenSource {
  id: string
  name: string
  width: number
  height: number
  isDisplay: boolean
}
export interface AudioDevice {
  id: string
  name: string
  deviceType: string
}
export interface RecordingConfiguration {
  width?: number
  height?: number
  fps?: number
  showCursor?: boolean
  captureAudio?: boolean
  audioDeviceId?: string
  outputPath: string
  pixelFormat?: string
  colorSpace?: string
}
export declare function initScreencapturekit(): void
export declare function getVersion(): string
export declare function checkMacosVersion(): string
export declare function testPhase2Implementation(): string
export declare class ScreenCaptureKitRecorder {
  constructor()
  getAvailableScreens(): Array<ScreenSource>
  getAvailableAudioDevices(): Array<AudioDevice>
  startRecording(screenId: string, config: RecordingConfiguration): void
  stopRecording(): string
  isRecording(): boolean
  getStatus(): string
}
